apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-node2
  namespace: cluster
spec:
  ports:
  - name: queue
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: admin
    port: 15672
    targetPort: 15672
    protocol: TCP
  - name: epmd
    port: 4369
    targetPort: 4369
    protocol: TCP
  - name: erlang
    port: 25672
    targetPort: 25672
    protocol: TCP
  selector:
    run: rabbitmq-node2
