apiVersion: v1
kind: Service
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq-cluster
  namespace: cluster
spec:
  clusterIP: None
  ports:
  - name: queue
    port: 5672
    protocol: TCP
  - name: epmd
    port: 4369
    protocol: TCP
  - name: erlang
    port: 25672
    protocol: TCP
  selector:
    run: rabbitmq

