apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-node3
  namespace: cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmq-node3
        cluster-node: rabbitmq-node
      annotations:
        "pod.beta.kubernetes.io/hostname": rabbitmq-node3
    spec:
      containers:
      - name: rabbitmq-node3
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 216Mi
        image: rabbitmq:3.6-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 4369
        - containerPort: 25672
        - containerPort: 55950
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-storage
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: "cluster_cookie"
      volumes:
      - name: rabbitmq-storage
        hostPath:
          path: /mnt/kube_common/cluster-rabbitmq/data
