apiVersion: v1
kind: Service
metadata:
  name: rabbitmqmaster
  namespace: cluster
spec:
  type: NodePort
  ports:
  - name: queue
    nodePort: 30022
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: admin
    nodePort: 30023
    port: 15672
    targetPort: 15672
    protocol: TCP
  - name: epmd
    nodePort: 30024
    port: 4369
    targetPort: 4369
    protocol: TCP
  - name: erlang
    nodePort: 30025
    port: 25672
    targetPort: 25672
    protocol: TCP
  selector:
    run: rabbitmq-master
