apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: cluster
spec:
  serviceName: rabbitmq
  replicas: 5
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: gpolunin/rabbitmq:test
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 4369
        - containerPort: 25672
        - containerPort: 55950
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-storage
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: "cluster_cookie"
        - name: AUTOCLUSTER_CLEANUP
          value: "true"
        - name: CLEANUP_INTERVAL
          value: "60"
        - name: CLEANUP_WARN_ONLY
          value: "true"
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RABBITMQ_NODENAME
          value: rabbit@$(NODE_NAME)

      volumes:
      - name: rabbitmq-storage
        hostPath:
          path: /mnt/kube_common/cluster-rabbitmq/data